apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.es.service.data.name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.es.service.data.type }}
  ports:
  - port: {{ .Values.es.service.data.externalTransportPort }}
    targetPort: transport
    protocol: TCP
    name: transport
  clusterIP: None
  selector:
{{ include "labels.esData" . | indent 4 }}
