apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.es.service.master.name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  ports:
  - port: {{ .Values.es.service.master.externalTransportPort }}
    targetPort: transport
    protocol: TCP
    name: transport
  selector:
{{ include "labels.esMaster" . | indent 4 }}
