apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "filebeat.fullname" . }}-config
  labels:
{{ include "labels" . | indent 4 }}
data:
  filebeat.yml: |-
    filebeat.config:
      # Filebeat can load external configuration files for prospectors and modules,
      # which allows you to separate your configuration into multiple smaller configuration files.
      # See: https://www.elastic.co/guide/en/beats/filebeat/6.2/filebeat-configuration-reloading.html#load-prospector-config
      prospectors:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    #processors:
    #  - add_cloud_metadata:

    #cloud.id: ${ELASTIC_CLOUD_ID}
    #cloud.auth: ${ELASTIC_CLOUD_AUTH}

{{- if .Values.logstash.enabled }}
    output.logstash:
      hosts: ['${LOGSTASH_HOST:logstash}:${LOGSTASH_PORT:5044}']
{{- else }}
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      #username: ${ELASTICSEARCH_USERNAME}
      #password: ${ELASTICSEARCH_PASSWORD
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "filebeat.fullname" . }}-prospectors
  labels:
{{ include "labels" . | indent 4 }}
data:
  kubernetes.yml: |-
    # See: https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-docker.html
    - type: docker
      containers.ids:
      - "*"
      # See: https://www.elastic.co/guide/en/beats/filebeat/6.2/add-kubernetes-metadata.html
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
