apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.kibana.service.name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
  - port: {{ .Values.kibana.service.externalPort }}
    targetPort: kibana
{{- if .Values.selectPort }}
    nodePort: {{ .Values.kibana.service.nodePort }}
{{- end }}
    protocol: TCP
    name: kibana
  selector:
{{ include "labels.kibana" . | indent 4 }}
