global:
  image:
    pullPolicy: Always
  volumes:
    keep: false
  storageClassName: rbd
es:
  replicaCount: 
    master: 3
    data: 2
    coordinator: 2
  heapSize:
    master: 1g
    data: 4g
    coordinator: 2g
  image:
    repository: elastic/elasticsearch
    tag: 6.2.4
  service:
    master:
      name: es-discovery
      type: ClusterIP
      externalTransportPort: 9300
      internalTransportPort: 9300
    data:
      name: es-data
      type: ClusterIP
      externalTransportPort: 9300
      internalTransportPort: 9300
    coordinator:
      name: es-coordinator
      type: ClusterIP
      externalApiPort: 9200
      internalApiPort: 9200
      externalTransportPort: 9300
      internalTransportPort: 9300
      nodePort: 30011
  volumes:
    master:
      storageClassName: rbd
      accessModes: ReadWriteOnce
      size: 4Gi
      mountPath: /usr/share/elasticsearch/data
    data:
      storageClassName: rbd
      accessModes: ReadWriteOnce
      size: 30Gi
      mountPath: /usr/share/elasticsearch/data
  cluster:
    name: elk
    env:
      # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
      # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
      # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
      MINIMUM_MASTER_NODES: "2"
selectPort: true
